# Generated by Django 5.2.6 on 2025-09-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekdays',
            name='name',
            field=models.CharField(choices=[('SAT', 'Saturday'), ('SUN', 'Sunday'), ('MON', 'monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday')], max_length=4),
        ),
    ]
