# Generated by Django 5.2.6 on 2025-09-29 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_alter_weekdays_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'educational_group': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='courses',
            name='students',
            field=models.ManyToManyField(blank=True, limit_choices_to={'educational_group': 'student'}, related_name='students_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
