# Generated by Django 5.2.6 on 2025-09-29 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_alter_courses_teacher_alter_courses_students_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='students',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='week_days',
        ),
        migrations.DeleteModel(
            name='Avatars',
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
        migrations.DeleteModel(
            name='WeekDays',
        ),
    ]
