# Generated by Django 5.2.6 on 2025-09-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='educational_group',
            field=models.CharField(blank=True, choices=[('teacher', 'teacher'), ('student', 'student'), ('admin', 'admin')], default='', max_length=7, null=True),
        ),
    ]
