# Generated by Django 5.2.6 on 2025-09-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='total_time',
            field=models.IntegerField(default=0),
        ),
    ]
