# Generated by Django 5.2.6 on 2025-09-29 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_admin', '0003_homeworks_sessions_studenthomework'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeworks',
            name='is_done_by',
        ),
    ]
