# Generated by Django 5.2.6 on 2025-09-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_admin', '0004_remove_homeworks_is_done_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='is_done',
            field=models.BooleanField(default=True),
        ),
    ]
